export enum UserRole {
  RESIDENT = 'resident',
  LEADER = 'leader',
  OFFICER = 'officer',
}

export enum AccountStatus {
  PENDING = 'pending',
  ACTIVE = 'active',
  LOCKED = 'locked',
  REJECTED = 'rejected',
}

export enum AnnouncementScope {
  WARD = 'ward',
  NEIGHBORHOOD = 'neighborhood',
}

export enum AnnouncementStatus {
  PUBLISHED = 'published',
  REMOVED = 'removed',
}

export enum NotificationType {
  ANNOUNCEMENT = 'announcement',
  COMMENT = 'comment',
  PETITION = 'petition',
  SYSTEM = 'system',
}

export enum PetitionCategory {
  INFRASTRUCTURE = 'infrastructure',
  SANITATION = 'sanitation',
  SECURITY = 'security',
  OTHER = 'other',
}

export enum PetitionStatus {
  REVIEWING = 'reviewing',
  PROCESSING = 'processing',
  RESOLVED = 'resolved',
  REJECTED = 'rejected',
  CANCELLED = 'cancelled',
}

export enum ReportingPeriodType {
  MONTH = 'month',
  QUARTER = 'quarter',
}

export enum ErrorCode {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_LOCKED = 'OTP_LOCKED',
  OTP_EXPIRED = 'OTP_EXPIRED',
  ACCOUNT_PENDING = 'ACCOUNT_PENDING',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_REGISTER_TOKEN = 'INVALID_REGISTER_TOKEN',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NEIGHBORHOOD_NOT_FOUND = 'NEIGHBORHOOD_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CSRF_ERROR = 'CSRF_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  REASON_REQUIRED = 'REASON_REQUIRED',
  ANNOUNCEMENT_NOT_FOUND = 'ANNOUNCEMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  ANNOUNCEMENT_REMOVED = 'ANNOUNCEMENT_REMOVED',
  INVALID_ATTACHMENT = 'INVALID_ATTACHMENT',
  ATTACHMENT_TOO_LARGE = 'ATTACHMENT_TOO_LARGE',
  TOO_MANY_ATTACHMENTS = 'TOO_MANY_ATTACHMENTS',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  INVALID_SCOPE = 'INVALID_SCOPE',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  PETITION_NOT_FOUND = 'PETITION_NOT_FOUND',
  PETITION_EVIDENCE_NOT_FOUND = 'PETITION_EVIDENCE_NOT_FOUND',
  INVALID_PETITION_CATEGORY = 'INVALID_PETITION_CATEGORY',
  INVALID_PETITION_STATUS = 'INVALID_PETITION_STATUS',
  INVALID_PETITION_TRANSITION = 'INVALID_PETITION_TRANSITION',
  PETITION_REJECTION_REASON_REQUIRED = 'PETITION_REJECTION_REASON_REQUIRED',
  PETITION_CANNOT_BE_CANCELLED = 'PETITION_CANNOT_BE_CANCELLED',
  TOO_MANY_PETITION_EVIDENCES = 'TOO_MANY_PETITION_EVIDENCES',
  INVALID_EVIDENCE_TYPE = 'INVALID_EVIDENCE_TYPE',
  EVIDENCE_TOO_LARGE = 'EVIDENCE_TOO_LARGE',
  INVALID_EVIDENCE = 'INVALID_EVIDENCE',
}
