export enum UserRole {
  RESIDENT = 'resident',
  LEADER = 'leader',
  OFFICER = 'officer',
}

export enum AccountStatus {
  PENDING = 'pending',
  ACTIVE = 'active',
  LOCKED = 'locked',
  REJECTED = 'rejected',
}

export enum ErrorCode {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_LOCKED = 'OTP_LOCKED',
  OTP_EXPIRED = 'OTP_EXPIRED',
  ACCOUNT_PENDING = 'ACCOUNT_PENDING',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_REGISTER_TOKEN = 'INVALID_REGISTER_TOKEN',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NEIGHBORHOOD_NOT_FOUND = 'NEIGHBORHOOD_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CSRF_ERROR = 'CSRF_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  REASON_REQUIRED = 'REASON_REQUIRED',
}
