export enum UserRole {
  RESIDENT = 'resident',
  LEADER = 'leader',
  OFFICER = 'officer',
}

export enum AccountStatus {
  PENDING = 'pending',
  ACTIVE = 'active',
  LOCKED = 'locked',
  REJECTED = 'rejected',
}

export enum AnnouncementScope {
  WARD = 'ward',
  NEIGHBORHOOD = 'neighborhood',
}

export enum AnnouncementStatus {
  PUBLISHED = 'published',
  REMOVED = 'removed',
}

export enum NotificationType {
  ANNOUNCEMENT = 'announcement',
  COMMENT = 'comment',
  PETITION = 'petition',
  SYSTEM = 'system',
}

export enum PetitionCategory {
  INFRASTRUCTURE = 'infrastructure',
  SANITATION = 'sanitation',
  SECURITY = 'security',
  OTHER = 'other',
}

export enum PetitionStatus {
  REVIEWING = 'reviewing',
  PROCESSING = 'processing',
  RESOLVED = 'resolved',
  REJECTED = 'rejected',
  CANCELLED = 'cancelled',
}

export enum ReportingPeriodType {
  MONTH = 'month',
  QUARTER = 'quarter',
}

export enum Gender {
  MALE = 'male',
  FEMALE = 'female',
  OTHER = 'other',
}

export enum PartyStatus {
  PARTY_MEMBER = 'party_member',
  UNDER_CONSIDERATION = 'under_consideration',
  NOT_MEMBER = 'not_member',
}

export enum HighestEducation {
  LOWER_SECONDARY = 'lower_secondary',
  UPPER_SECONDARY = 'upper_secondary',
  VOCATIONAL = 'vocational',
  COLLEGE = 'college',
  BACHELOR = 'bachelor',
  MASTER = 'master',
  DOCTORATE = 'doctorate',
}

export enum ActivityFilterCondition {
  ALL = 'all',
  UNDER_18 = 'under_18',
  OVER_18 = 'over_18',
  PARTY_MEMBER = 'party_member',
  CUSTOM = 'custom',
}

export enum AttendanceStatus {
  ATTENDED = 'attended',
  ABSENT = 'absent',
  UNCONFIRMED = 'unconfirmed',
}

export enum ActivityRating {
  GOOD = 'good',
  FAIR = 'fair',
  AVERAGE = 'average',
}

export enum ErrorCode {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_LOCKED = 'OTP_LOCKED',
  OTP_EXPIRED = 'OTP_EXPIRED',
  ACCOUNT_PENDING = 'ACCOUNT_PENDING',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_REGISTER_TOKEN = 'INVALID_REGISTER_TOKEN',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NEIGHBORHOOD_NOT_FOUND = 'NEIGHBORHOOD_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CSRF_ERROR = 'CSRF_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  REASON_REQUIRED = 'REASON_REQUIRED',
  ANNOUNCEMENT_NOT_FOUND = 'ANNOUNCEMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  ANNOUNCEMENT_REMOVED = 'ANNOUNCEMENT_REMOVED',
  INVALID_ATTACHMENT = 'INVALID_ATTACHMENT',
  ATTACHMENT_TOO_LARGE = 'ATTACHMENT_TOO_LARGE',
  TOO_MANY_ATTACHMENTS = 'TOO_MANY_ATTACHMENTS',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  INVALID_SCOPE = 'INVALID_SCOPE',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  PETITION_NOT_FOUND = 'PETITION_NOT_FOUND',
  PETITION_EVIDENCE_NOT_FOUND = 'PETITION_EVIDENCE_NOT_FOUND',
  INVALID_PETITION_CATEGORY = 'INVALID_PETITION_CATEGORY',
  INVALID_PETITION_STATUS = 'INVALID_PETITION_STATUS',
  INVALID_PETITION_TRANSITION = 'INVALID_PETITION_TRANSITION',
  PETITION_REJECTION_REASON_REQUIRED = 'PETITION_REJECTION_REASON_REQUIRED',
  PETITION_CANNOT_BE_CANCELLED = 'PETITION_CANNOT_BE_CANCELLED',
  TOO_MANY_PETITION_EVIDENCES = 'TOO_MANY_PETITION_EVIDENCES',
  INVALID_EVIDENCE_TYPE = 'INVALID_EVIDENCE_TYPE',
  EVIDENCE_TOO_LARGE = 'EVIDENCE_TOO_LARGE',
  INVALID_EVIDENCE = 'INVALID_EVIDENCE',
  CITIZEN_ID_ALREADY_EXISTS = 'CITIZEN_ID_ALREADY_EXISTS',
  RESIDENT_PROFILE_NOT_FOUND = 'RESIDENT_PROFILE_NOT_FOUND',
  HOUSEHOLD_NOT_FOUND = 'HOUSEHOLD_NOT_FOUND',
  INVALID_CITIZEN_ID = 'INVALID_CITIZEN_ID',
  POLITICAL_SOCIAL_PROFILE_NOT_FOUND = 'POLITICAL_SOCIAL_PROFILE_NOT_FOUND',
  ACTIVITY_NOT_FOUND = 'ACTIVITY_NOT_FOUND',
  INVALID_ACTIVITY_DATE = 'INVALID_ACTIVITY_DATE',
  INVALID_PARTICIPANT = 'INVALID_PARTICIPANT',
  DUPLICATE_PARTICIPANT = 'DUPLICATE_PARTICIPANT',
}
